// Use hs upload to move the ui extension project to the developer account portal (Pearagon development).
// Deploy the backend REST server
// Copy the environment variables (CLIENT_ID, CLIENT_SECRET, etc..) from developer account portal to server
// Using the backend server, install the public app into the production portal
// Save the refresh token generated by the installation into the server's env file
// If the app is uninstalled, a new refresh token must be set again in the server's env file

const dotenv = require("dotenv");
const path = require("path");
const express = require("express");
const axios = require("axios");
const hubspot = require("@hubspot/api-client");
const { saveData } = require("./saveData");
const { initialSaveData } = require("./initialSaveData");

const app = express();

let accessToken;

const env = process.env.NODE_ENV || "development";

dotenv.config({
  path: path.resolve(__dirname, `config/${env}.env`),
});

const PORT = process.env.PORT;
const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const SCOPES = process.env.SCOPES;
const TICKET_PIPELINE_TO_CHECK = process.env.TICKET_PIPELINE_TO_CHECK;
const REDIRECT_URI = process.env.REDIRECT_URI;
const REFRESH_TOKEN = process.env.REFRESH_TOKEN;
const GOOGLE_API_URL = process.env.GOOGLE_API_URL;

if (!CLIENT_ID || !CLIENT_SECRET) {
  throw new Error("Missing CLIENT_ID or CLIENT_SECRET environment variable.");
}

const refreshAccessToken = async (refreshToken) => {
  const refreshTokenProof = {
    grant_type: "refresh_token",
    client_id: CLIENT_ID,
    client_secret: CLIENT_SECRET,
    redirect_uri: REDIRECT_URI,
    refresh_token: refreshToken,
  };
  await exchangeForTokens(refreshTokenProof);
};

const getInitialTokens = async (code) => {
  const authorizationProof = {
    grant_type: "authorization_code",
    client_id: CLIENT_ID,
    client_secret: CLIENT_SECRET,
    redirect_uri: REDIRECT_URI,
    code: code,
  };
  return await exchangeForTokens(authorizationProof);
};

const exchangeForTokens = async (exchangeProof) => {
  // console.log(JSON.stringify(exchangeProof));

  try {
    const response = await axios.post("https://api.hubapi.com/oauth/v1/token", null, {
      params: exchangeProof,
    });

    const newRefreshToken = response.data.refresh_token;
    const newAccessToken = response.data.access_token;
    const expiresIn = response.data.expires_in;

    // console.log("Refresh Token", newRefreshToken);
    // console.log("Access Token", newAccessToken);
    // console.log("Expires In", expiresIn);

    setToken(newAccessToken, expiresIn);
    console.log("Access token is set");

    return { accessToken: newAccessToken, refreshToken: newRefreshToken };
  } catch (error) {
    console.error(`Error exchanging ${exchangeProof.grant_type} for access token`);
    throw error;
  }
};

const setToken = (token, expiresIn) => {
  accessToken = token;

  setTimeout(() => {
    accessToken = null;
    console.log("Access token has expired and been deleted");
  }, expiresIn * 1000);
};

const getAccessToken = async () => {
  if (!accessToken) {
    console.log("Refreshing expired access token");
    await refreshAccessToken(REFRESH_TOKEN);
  }
  return accessToken;
};

const ticketsInAnalysisPipeline = async (accessToken, dealId, ticketPipelineToCheck) => {
  // console.log("accessToken", accessToken);

  const hubspotClient = new hubspot.Client({ accessToken: accessToken });

  try {
    const response = await hubspotClient.crm.tickets.searchApi.doSearch({
      filterGroups: [
        {
          filters: [
            {
              propertyName: "associations.deal",
              operator: "EQ",
              value: dealId,
            },
            {
              propertyName: "hs_pipeline",
              operator: "EQ",
              value: ticketPipelineToCheck,
            },
          ],
        },
      ],
      after: "",
      limit: 50,
      properties: [
        "building_type",
        "cost_basis",
        "property_placed_in_service_date",
        "property_5yr_est",
        "property_7yr_est",
        "property_15yr_est",
        "subject_property_address_1",
        "subject_property_city",
        "subject_property_state",
        "subject_property_zip_code",
        "property__bonus__year_applied",
        "fees",
        "projected_additional_depreciation",
        "tax_impact_on_depreciation_difference",
        "after_tax_study_fee",
      ],
      sorts: [""],
    });

    return response;
  } catch (error) {
    console.error("Error!!", error.message);
    throw error;
  }
};

app.get("/install", (req, res) => {
  const authUrl = `https://app.hubspot.com/oauth/authorize?client_id=${encodeURIComponent(CLIENT_ID)}&scope=${encodeURIComponent(SCOPES)}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}`;
  res.redirect(authUrl);
});

app.get("/oauth-callback", async (req, res) => {
  const { code } = req.query;

  if (!code) {
    return res.status(400).send("No authorization code provided.");
  }

  try {
    const tokens = await getInitialTokens(code);
    res.send(`Access Token: ${tokens.accessToken} Refresh Token: ${tokens.refreshToken}`);
  } catch (error) {
    console.error("Error exchanging code for token:", error.response.data);
    res.status(500).send("Error exchanging code for token");
  }
});

app.get("/get-data", async (req, res) => {
  const dealRecordID = req.query.dealId; // || "22678534467"; // TODO: remove default value for testing
  const accessToken = await getAccessToken();
  // console.log(`Deal Record ID ${dealRecordID}`);

  try {
    const ticketsInAnalysisPipelineData = await ticketsInAnalysisPipeline(accessToken, dealRecordID, TICKET_PIPELINE_TO_CHECK);
    console.log(JSON.stringify(ticketsInAnalysisPipelineData));
    res.status(200).json(ticketsInAnalysisPipelineData);
  } catch (error) {
    const errorMessage = error.response?.data?.message || error.message || "An unknown error occurred";
    console.error("Error making request:", errorMessage);
    res.status(500).json({ error: errorMessage });
  }
});

app.get("/error", (req, res) => {
  res.setHeader("Content-Type", "text/html");
  res.write(`<h4>Error: ${req.query.msg}</h4>`);
  res.end();
});

app.get("/hello", (req, res) => {
  res.status(200).json({ message: "Activated from workflow" });
});

app.use(express.json());

app.patch("/save-data", async (req, res) => {
  const accessToken = await getAccessToken();
  const { ticketId, fees } = req.body;
  await saveData(GOOGLE_API_URL, accessToken, ticketId, fees);
  res.status(200).json({ message: "save finished" });
});

app.patch("/initial-save-data", async (req, res) => {
  const accessToken = await getAccessToken();
  const { dealId } = req.body;
  await initialSaveData(GOOGLE_API_URL, accessToken, dealId);
  res.status(200).json({ message: "initial save finished" });
});

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
