// Use hs upload to move the ui extension project to the developer account portal (Pearagon development).
// Deploy the backend REST server
// Copy the environment variables (CLIENT_ID, CLIENT_SECRET, etc..) from developer account portal to server
// Using the backend server, install the public app into the production portal
// Save the refresh token generated by the installation into the server's env file
// If the app is uninstalled, a new refresh token must be set again in the server's env file

const dotenv = require("dotenv");
const path = require("path");
const express = require("express");
const axios = require("axios");
const hubspot = require("@hubspot/api-client");
const crypto = require("crypto");
const validateHubSpotSignature = require("./middleware/validateHubSpotSignature");
const bodyParser = require("body-parser");

const app = express();

let accessToken;

const env = process.env.NODE_ENV || "development";
console.log("ENV", env);

dotenv.config({
    path: path.resolve(__dirname, `config/${env}.env`),
});

const PORT = process.env.PORT;
const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const SCOPES = process.env.SCOPES;
const REDIRECT_URI = process.env.REDIRECT_URI;
const REFRESH_TOKEN = process.env.REFRESH_TOKEN;

console.log("PORT", PORT);
console.log("CLIENT_ID", CLIENT_ID);
console.log("CLIENT_SECRET", CLIENT_SECRET);

if (!CLIENT_ID || !CLIENT_SECRET) {
    throw new Error("Missing CLIENT_ID or CLIENT_SECRET environment variable.");
}

const refreshAccessToken = async (refreshToken) => {
    const refreshTokenProof = {
        grant_type: "refresh_token",
        client_id: CLIENT_ID,
        client_secret: CLIENT_SECRET,
        redirect_uri: REDIRECT_URI,
        refresh_token: refreshToken,
    };
    await exchangeForTokens(refreshTokenProof);
};

const getInitialTokens = async (code) => {
    const authorizationProof = {
        grant_type: "authorization_code",
        client_id: CLIENT_ID,
        client_secret: CLIENT_SECRET,
        redirect_uri: REDIRECT_URI,
        code: code,
    };
    return await exchangeForTokens(authorizationProof);
};

const exchangeForTokens = async (exchangeProof) => {
    // console.log(JSON.stringify(exchangeProof));

    try {
        const response = await axios.post("https://api.hubapi.com/oauth/v1/token", null, {
            params: exchangeProof,
        });

        const newRefreshToken = response.data.refresh_token;
        const newAccessToken = response.data.access_token;
        const expiresIn = response.data.expires_in;

        // console.log("Refresh Token", newRefreshToken);
        // console.log("Access Token", newAccessToken);
        // console.log("Expires In", expiresIn);

        setToken(newAccessToken, expiresIn);
        console.log("Access token is set");

        return { accessToken: newAccessToken, refreshToken: newRefreshToken };
    } catch (error) {
        console.error(`Error exchanging ${exchangeProof.grant_type} for access token`);
        throw error;
    }
};

const setToken = (token, expiresIn) => {
    accessToken = token;

    setTimeout(() => {
        accessToken = null;
        console.log("Access token has expired and been deleted");
    }, expiresIn * 1000);
};

const getAccessToken = async () => {
    if (!accessToken) {
        console.log("Refreshing expired access token");
        await refreshAccessToken(REFRESH_TOKEN);
    }
    return accessToken;
};

app.get("/install", (req, res) => {
    const authUrl = `https://app.hubspot.com/oauth/authorize?client_id=${encodeURIComponent(CLIENT_ID)}&scope=${encodeURIComponent(SCOPES)}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}`;
    res.redirect(authUrl);
});

app.get("/oauth-callback", async (req, res) => {
    const { code } = req.query;

    if (!code) {
        return res.status(400).send("No authorization code provided.");
    }

    try {
        const tokens = await getInitialTokens(code);
        res.send(`Access Token: ${tokens.accessToken} Refresh Token: ${tokens.refreshToken}`);
    } catch (error) {
        console.error("Error exchanging code for token:", error.response.data);
        res.status(500).send("Error exchanging code for token");
    }
});

app.get("/error", (req, res) => {
    res.setHeader("Content-Type", "text/html");
    res.write(`<h4>Error: ${req.query.msg}</h4>`);
    res.end();
});

app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// app.get("/hello", validateHubSpotSignature(CLIENT_SECRET), (req, res) => {
app.get("/hello", (req, res) => {
    res.status(200).json({ message: "Signature is valid therefore, hello!" });
});

app.post("/webhook-test", (request, response) => {
    response.status(200).send("Received webhook subscription trigger");

    const { url, method, body, headers, hostname } = request;

    // Parse headers needed to validate signature
    const signatureHeader = headers["x-hubspot-signature-v3"];
    const timestampHeader = headers["x-hubspot-request-timestamp"];

    // Validate timestamp
    const MAX_ALLOWED_TIMESTAMP = 300000; // 5 minutes in milliseconds
    const currentTime = Date.now();
    if (currentTime - timestampHeader > MAX_ALLOWED_TIMESTAMP) {
        console.log("Timestamp is invalid, reject request");
        // Add any rejection logic here
    }

    // Concatenate request method, URI, body, and header timestamp
    const uri = `https://${hostname}${url}`;
    const rawString = `${method}${uri}${JSON.stringify(body)}${timestampHeader}`;

    // Create HMAC SHA-256 hash from resulting string above, then base64-encode it
    const hashedString = crypto.createHmac("sha256", process.env.CLIENT_SECRET).update(rawString).digest("base64");

    // Validate signature: compare computed signature vs. signature in header
    if (crypto.timingSafeEqual(Buffer.from(hashedString), Buffer.from(signatureHeader))) {
        console.log("Signature matches! Request is valid.");
        // Proceed with any request processing as needed.
    } else {
        console.log("Signature does not match: request is invalid");
        // Add any rejection logic here.
    }
});

app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
