// Use hs upload to move the ui extension project to the developer account portal (Pearagon development).
// Deploy the backend REST server
// Copy the environment variables (CLIENT_ID, CLIENT_SECRET, etc..) from developer account portal to server
// Using the backend server, install the public app into the production portal
// Save the refresh token generated by the installation into the server's env file
// If the app is uninstalled, a new refresh token must be set again in the server's env file

const dotenv = require('dotenv');
const path = require('path');
const express = require('express');
const axios = require('axios');
const hubspot = require('@hubspot/api-client');

const app = express();

let accessToken;

const env = process.env.NODE_ENV || 'development';

dotenv.config({
  path: path.resolve(__dirname, `config/${env}.env`),
});

const PORT = process.env.PORT;
const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const SCOPES = process.env.SCOPES;
const REDIRECT_URI = process.env.REDIRECT_URI;
const REFRESH_TOKEN = process.env.REFRESH_TOKEN;

if (!CLIENT_ID || !CLIENT_SECRET) {
  throw new Error('Missing CLIENT_ID or CLIENT_SECRET environment variable.');
}

const refreshAccessToken = async (refreshToken) => {
  const refreshTokenProof = {
    grant_type: 'refresh_token',
    client_id: CLIENT_ID,
    client_secret: CLIENT_SECRET,
    redirect_uri: REDIRECT_URI,
    refresh_token: refreshToken,
  };
  await exchangeForTokens(refreshTokenProof);
};

const getInitialTokens = async (code) => {
  const authorizationProof = {
    grant_type: 'authorization_code',
    client_id: CLIENT_ID,
    client_secret: CLIENT_SECRET,
    redirect_uri: REDIRECT_URI,
    code: code,
  };
  return await exchangeForTokens(authorizationProof);
};

const exchangeForTokens = async (exchangeProof) => {
  // console.log(JSON.stringify(exchangeProof));

  try {
    const response = await axios.post('https://api.hubapi.com/oauth/v1/token', null, {
      params: exchangeProof,
    });

    const newRefreshToken = response.data.refresh_token;
    const newAccessToken = response.data.access_token;
    const expiresIn = response.data.expires_in;

    // console.log("Refresh Token", newRefreshToken);
    // console.log("Access Token", newAccessToken);
    // console.log("Expires In", expiresIn);

    setToken(newAccessToken, expiresIn);
    console.log('Access token is set');

    return { accessToken: newAccessToken, refreshToken: newRefreshToken };
  } catch (error) {
    console.error(`Error exchanging ${exchangeProof.grant_type} for access token`);
    throw error;
  }
};

const setToken = (token, expiresIn) => {
  accessToken = token;

  setTimeout(() => {
    accessToken = null;
    console.log('Access token has expired and been deleted');
  }, expiresIn * 1000);
};

const getAccessToken = async () => {
  if (!accessToken) {
    console.log('Refreshing expired access token');
    await refreshAccessToken(REFRESH_TOKEN);
  }
  return accessToken;
};

app.get('/install', (req, res) => {
  const authUrl = `https://app.hubspot.com/oauth/authorize?client_id=${encodeURIComponent(CLIENT_ID)}&scope=${encodeURIComponent(SCOPES)}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}`;
  res.redirect(authUrl);
});

app.get('/oauth-callback', async (req, res) => {
  const { code } = req.query;

  if (!code) {
    return res.status(400).send('No authorization code provided.');
  }

  try {
    const tokens = await getInitialTokens(code);
    res.send(`Access Token: ${tokens.accessToken} Refresh Token: ${tokens.refreshToken}`);
  } catch (error) {
    console.error('Error exchanging code for token:', error.response.data);
    res.status(500).send('Error exchanging code for token');
  }
});

app.get('/error', (req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.write(`<h4>Error: ${req.query.msg}</h4>`);
  res.end();
});

app.get('/hello', (req, res) => {
  res.status(200).json({ message: 'Hello!' });
});

// app.use(express.json());

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
